{"wad": {"name": "Web app development",
                       "ID": "COMPSCI 2021",
                       "url": "https://www.gla.ac.uk/coursecatalogue/course/?code=COMPSCI2021",
                       "taught_by": "David Manlove",
                       "description": "The aim of this course is to provide students with a comprehensive overview of web application development. It will provide students with the skills to design and develop distributed web applications in a disciplined manner, using a range of tools and technologies. It will also strengthen their understanding of the context and rationale of distributed systems. ",
                       "requirements_of_entry": "Entry to Level 2 Computing Science is guaranteed to students who achieve a GPA of B3 or better in their level 1 courses at the first sitting. All others would be at the discretion of the School.All grades for Computing Science courses must be at D3 or better at either attempt. Strong python skills are a requirement for this course.",
                       "credits": 10,
                       "year": 2,
                       "school": "School of Computing Science",
                       "coursework": wad_coursework, },
