# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-16 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(max_length=30, unique=True)),
                ('taught_by', models.CharField(max_length=30)),
                ('description', models.TextField(default='')),
                ('required_grades', models.CharField(default='', max_length=49)),
                ('credits', models.IntegerField(max_length=3)),
                ('year', models.IntegerField(max_length=3)),
                ('school', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CourseWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GUID', models.FloatField(max_length=7, unique=True)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('GPA', models.IntegerField(max_length=3)),
            ],
        ),
    ]
