# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-16 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradinator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='coursework',
            name='weight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='GPA',
            field=models.IntegerField(),
        ),
    ]
