# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-16 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradinator', '0002_auto_20190316_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='ID',
            new_name='courseID',
        ),
    ]
