# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-17 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradinator', '0003_auto_20190316_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='courseID',
            new_name='ID',
        ),
    ]
