# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-17 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradinator', '0004_auto_20190317_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='ID',
            new_name='courseID',
        ),
    ]
